version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/tgs/
    binary: tgs
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/searchtgcli/tgs/internal/cmd.Version={{.Version}}
      - -X github.com/searchtgcli/tgs/internal/cmd.Commit={{.ShortCommit}}
      - -X github.com/searchtgcli/tgs/internal/cmd.Date={{.Date}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

brews:
  - repository:
      owner: garenal1v3
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: "https://github.com/garenal1v3/tgs-cli"
    description: "Fast CLI client for searching Telegram"
    license: "GPL-3.0"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
